language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - docker build -t radium .
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag radium $DOCKER_USERNAME/radium:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/radium:$TRAVIS_BUILD_NUMBER
  - docker tag radium $DOCKER_USERNAME/radium:latest
  - docker push $DOCKER_USERNAME/radium:latest
